// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// // export const metadata: Metadata = {
// //   title: "Create Next App",
// //   description: "Generated by create next app",
// // };

// export const metadata = {
//   title: "Crane Core Group — Join the Waitlist",
//   description:
//     "Crane Core Group is building infrastructure for ambitious teams. Join the waitlist for early access.",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">{children}</body>
//     </html>
//   );
// }


// CLAUDE PERSONAL ACCOUNT
import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

/* ─────────────────────────────────────────────────────────────────────────────
   Fonts
   Geist Sans & Geist Mono are loaded here but DM Sans / DM Mono are imported
   directly inside page.tsx via a <style> block for the waitlist page's own
   design system. Both font sets are available across the app.
───────────────────────────────────────────────────────────────────────────── */

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});

/* ─────────────────────────────────────────────────────────────────────────────
   Viewport — controls mobile scaling behaviour
───────────────────────────────────────────────────────────────────────────── */

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  themeColor: "#04060e",
};

/* ─────────────────────────────────────────────────────────────────────────────
   Metadata — SEO, Open Graph, Twitter card
───────────────────────────────────────────────────────────────────────────── */

export const metadata: Metadata = {
  metadataBase: new URL(
    process.env.NEXT_PUBLIC_SITE_URL ?? "https://cranecoregroup.com"
  ),

  title: {
    default: "Crane Core Group — Blueprint Intelligence",
    template: "%s — Crane Core Group",
  },

  description:
    "AI systems that read construction blueprints and floor plans — automating planning, resource estimation, and execution for modern infrastructure teams. Request early access.",

  keywords: [
    "construction AI",
    "blueprint intelligence",
    "floor plan analysis",
    "construction automation",
    "infrastructure AI",
    "project estimation AI",
    "Crane Core Group",
  ],

  authors: [{ name: "Crane Core Group" }],

  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-snippet": -1,
      "max-image-preview": "large",
    },
  },

  openGraph: {
    type: "website",
    siteName: "Crane Core Group",
    title: "Crane Core Group — Blueprint Intelligence",
    description:
      "AI-driven systems that transform construction blueprints into actionable intelligence. Automate planning, estimation, and execution.",
    locale: "en_US",
  },

  twitter: {
    card: "summary",
    title: "Crane Core Group — Blueprint Intelligence",
    description:
      "AI that reads construction blueprints. Automating planning, estimation, and execution for infrastructure teams.",
  },
};

/* ─────────────────────────────────────────────────────────────────────────────
   Root layout
───────────────────────────────────────────────────────────────────────────── */

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable}`}
      suppressHydrationWarning
    >
      <body>{children}</body>
    </html>
  );
}